language: node_js
node_js:
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - npm install
  - npm install -g jspm && jspm install
  - npm install -g typings && typings install
script:
  - gulp test
  - gulp build
